//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zachet
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIO()
        {
            this.Jurnal = new HashSet<Jurnal>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> GodPostuplenia { get; set; }
        public Nullable<int> IdFormaTeaching { get; set; }
        public Nullable<int> IdCurs { get; set; }
    
        public virtual Curs Curs { get; set; }
        public virtual FormaTeaching FormaTeaching { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal> Jurnal { get; set; }
    }
}
