//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zachet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaDannixEntities : DbContext
    {
        public BazaDannixEntities()
            : base("name=BazaDannixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curs> Curs { get; set; }
        public virtual DbSet<Disceplina> Disceplina { get; set; }
        public virtual DbSet<FIO> FIO { get; set; }
        public virtual DbSet<FormaTeaching> FormaTeaching { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Jurnal> Jurnal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
